version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: your@email.com
      PGADMIN_DEFAULT_PASSWORD: yoursecretpassword
    ports:
      - "80:80"
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge